// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBysVcmlmt9j6Lofuj7A51cgONWvhCP0qk',
    appId: '1:367381584209:web:de3ea13fcd5088a047db70',
    messagingSenderId: '367381584209',
    projectId: 'cashflowdb-d4f0f',
    authDomain: 'cashflowdb-d4f0f.firebaseapp.com',
    storageBucket: 'cashflowdb-d4f0f.appspot.com',
    measurementId: 'G-KPQ64LRZNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCahP9wUoh0wbP5K6w4wwj3cNE0zXmUv0',
    appId: '1:367381584209:android:651cb24da3b8984947db70',
    messagingSenderId: '367381584209',
    projectId: 'cashflowdb-d4f0f',
    storageBucket: 'cashflowdb-d4f0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdQSgy5fEiAbQlq6U7YSyVw_o1dX0RpPM',
    appId: '1:367381584209:ios:a0096f7a31fabc2747db70',
    messagingSenderId: '367381584209',
    projectId: 'cashflowdb-d4f0f',
    storageBucket: 'cashflowdb-d4f0f.appspot.com',
    iosBundleId: 'com.example.flutterIt14proj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdQSgy5fEiAbQlq6U7YSyVw_o1dX0RpPM',
    appId: '1:367381584209:ios:6418cdddd8a36aeb47db70',
    messagingSenderId: '367381584209',
    projectId: 'cashflowdb-d4f0f',
    storageBucket: 'cashflowdb-d4f0f.appspot.com',
    iosBundleId: 'com.example.flutterIt14proj.RunnerTests',
  );
}
